const AUTOHEAL_CONFIG = {
  ENABLED: process.env.AUTOHEAL_ENABLED !== 'false',
  SCHEDULE_MINUTES: parseInt(process.env.AUTOHEAL_SCHEDULE_MINUTES || '15', 10),
  MAX_FIXES_PER_RUN: parseInt(process.env.AUTOHEAL_MAX_FIXES_PER_RUN || '25', 10),
  SAFE_MODE: process.env.AUTOHEAL_SAFE_MODE !== 'false',
  PLAYWRIGHT_BASE_URL: process.env.PLAYWRIGHT_BASE_URL || 'http://localhost:5000'
};

const FIX_ACTIONS = {
  DISABLE_NON_PET_PRODUCTS: 'DISABLE_NON_PET_PRODUCTS',
  REASSIGN_CATEGORY: 'REASSIGN_CATEGORY',
  REBUILD_RESOLVED_IMAGES: 'REBUILD_RESOLVED_IMAGES',
  ENABLE_REMOTE_IMAGE_FALLBACK: 'ENABLE_REMOTE_IMAGE_FALLBACK',
  REGENERATE_SEO_FOR_MISSING: 'REGENERATE_SEO_FOR_MISSING',
  RECALC_PRICES: 'RECALC_PRICES',
  CLEAR_CACHE_REINDEX: 'CLEAR_CACHE_REINDEX'
};

const ALLOWED_FIX_ACTIONS = Object.values(FIX_ACTIONS);

module.exports = {
  AUTOHEAL_CONFIG,
  FIX_ACTIONS,
  ALLOWED_FIX_ACTIONS
};
